### PR TITLE
Promote DuckDB, Arrow and Postgres Data Accelerators to Beta

### PR DESCRIPTION
**Pull request by sgrebnov**
## 🗣 Description

Promote DuckDB, Arrow and Postgres Data Accelerators to Beta (repo readme)

1. ~Arrow was not promoted as it does not satisfy the following beta criteria: `The accelerator supports resolving on conflict behaviors (e.g. Drop/Upsert)`~ Not applicable for Arrow.
2. SQLite was not promoted as it currently can't run TPC-DS SF1 / pending research so does not satisfy the following beta criteria: 
`End-to-end test to cover accelerating TPC-DS SF1 data from S3 and benchmarking TPC-DS queries (official and simple).`

### CODE REVIEW

**Comment by eadgbear** [comment]
There's a section in the Beta criteria about query correctness (matching accelerator/connector results with original source results) that we currently do not meet.

**Comment by sgrebnov** [comment]
> There's a section in the Beta criteria about query correctness (matching accelerator/connector results with original source results) that we currently do not meet.

**Comment by sgrebnov** [comment]
> There's a section in the Beta criteria about query correctness (matching accelerator/connector results with original source results) that we currently do not meet.

The approach for `query correctness` we will follow and update Beta/RC criteria accordingly:
1. TPC-H - all queries must satisfy query correctness 
2. TPC-DS -  it is fine to return the same incorrect result **if datafusion does the same** for Beta (currently have 1/2 such issues / ~6 TPC-DS queries affected).

**Comment by peasee** [comment]
The accelerator release tracking issues do not have all of their items marked as complete. We shouldn't promote them until they're complete, and the issues are closed:

* DuckDB: https://github.com/spiceai/spiceai/issues/3031
* Postgres: https://github.com/spiceai/spiceai/issues/3029
* Arrow: https://github.com/spiceai/spiceai/issues/3027

**Review by peasee — CHANGES_REQUESTED** [review]
The accelerators are not beta

**Comment by sgrebnov** [comment]
> * Accelerator Beta Release: PostgreSQL #3029

Good point, I thought those are for RC release, let me quickly go thru the checklist

**Comment by Sevenannn** [comment]
> > There's a section in the Beta criteria about query correctness (matching accelerator/connector results with original source results) that we currently do not meet.
> 
> The approach for `query correctness` we will follow and update Beta/RC criteria accordingly:
> 
> 1. TPC-H - all queries must satisfy query correctness
> 2. TPC-DS -  it is fine to return the same incorrect result **if datafusion does the same** for Beta (currently have 1/2 such issues / ~6 TPC-DS queries affected).

We will need to wait for benchmark test on trunk to verify DuckDB parity with Datafusion

**Pull request closed without merging**
