### PR TITLE
Fix optional connector features: duckdb, postgres, sqlite

### LINKED ISSUE #1025: `spiced` cannot be built with optional connectors
**Describe the bug**

One cannot build `spicedb` without `duckdb`. Firstly, top-level featurse are missing in `bin/spicedb/Cargo.toml`. Also, specifying workspace crate features, e.g. `"db_connection_pool/postgres"` doesn't control optional code and deps sufficiently.

**To Reproduce**

`cargo build --no-default-features --features "sqlite"` still includes `duckdb` and its sys crate.

**Expected behavior**

All of those run `spiced` with the requested connector support only:

`cargo run --no-default-features --features "sqlite"`
`cargo run --no-default-features --features "postgres"`
`cargo run --no-default-features --features "duckdb"`

Obviously any combintation should work too. The default features of `spicedb` shouldn't change.

**Additional context**

Some dependencies are heavy, in terms of build, platform and size requirements.
Going forward with #999 and #1000 aggrevates missing or not working top-level features.

I can work on that issue.

### PR DESCRIPTION
**Pull request by ahirner**
Closes #1025.

I opted to remove default features in sub-crates as its a saner way to end up with the right features from the workspace default member. Opinions and testing welcome.

### CODE REVIEW

**Comment by phillipleblanc** [comment]
This is awesome! Thank you.

**Review by phillipleblanc — APPROVED** [review]

**Comment by lukekim** [comment]
Thanks, @ahirner! Can you email me at luke@spice.ai and we'll send you a shirt.

**Comment by lukekim** [comment]
@ahirner it would also be great to add some docs to CONTRIBUTING.md for custom, feature specific builds.

**Comment by ahirner** [comment]
Will do.

**Pull request merged**
